version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: iam-ch7-keycloak
    command: 
      - start-dev --http-port 8180    
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8180:8180"
