version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: iam-ch4-keycloak
    command: 
      - start-dev    
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"    
  app:
    build: .
    image: iam-ch4-app
    container_name: iam-ch4-app
    ports:
      - "8000:8000"
    environment:
      KC_URL: http://localhost:8080