version: '3'

volumes:
  postgres_data:
    driver: local

# Keycloak common environment configuration using Extension fields format, @see: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields  
x-keycloak-environment: &keycloak-environment
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: password
  KC_HOSTNAME: mykeycloak
  KC_HOSTNAME_STRICT_BACKCHANNEL: true
  KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/mykeycloak.keystore
  KC_HTTPS_KEY_STORE_PASSWORD: password
  KC_PROXY: reencrypt

services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  kc1:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: iam-ch9-kc1
    command: 
      - start
    environment:
      << : *keycloak-environment
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15       
    volumes:
      - $PWD/mykeycloak.keystore:/opt/keycloak/conf/mykeycloak.keystore
    ports:
      - 8443:8443
    depends_on:
      - postgres
  kc2:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: iam-ch9-kc2
    command: 
      - start
    environment:
      << : *keycloak-environment
      KC_HTTP_PORT: 8180
      KC_HTTPS_PORT: 8543
    volumes:
      - $PWD/mykeycloak.keystore:/opt/keycloak/conf/mykeycloak.keystore
    ports:
      - 8543:8543
    depends_on:
      kc1:
        condition: service_healthy
  kc3:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: iam-ch9-kc3
    command: 
      - start
    environment:
      << : *keycloak-environment
      KC_HTTP_PORT: 8280
      KC_HTTPS_PORT: 8643
    volumes:
      - $PWD/mykeycloak.keystore:/opt/keycloak/conf/mykeycloak.keystore
    ports:
      - 8643:8643
    depends_on:  
      kc1:
        condition: service_healthy       
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - $PWD/haproxy.crt.pem:/etc/haproxy/haproxy.crt.pem  
    ports:
      - 443:443  
    depends_on:
      kc1:
        condition: service_healthy